// apps/web/src/pages/sitemap.xml.ts
import type { APIRoute } from "astro";

const SITE_URL = import.meta.env.SITE_URL || "https://evergreenplumbingri.com";
const API_URL = import.meta.env.PUBLIC_API_URL;

interface Service {
  slug: string;
  title: string;
  updatedAt: string;
}

interface Post {
  slug: string;
  title: string;
  updatedAt: string;
}

interface Job {
  slug: string;
  title: string;
  updatedAt: string;
}

const staticPages = [
  { url: "/", title: "Home" },
  { url: "/about-us", title: "About Us" },
  { url: "/contact-us", title: "Contact Us" },
  { url: "/customer-service", title: "Customer Service" },
  { url: "/24-7-emergency-services", title: "24/7 Emergency Services" },
  { url: "/financing-options-plans", title: "Financing Options & Plans" },
  { url: "/maintenance-plan", title: "Maintenance Plans" },
  { url: "/careers", title: "Careers" },
  { url: "/our-guarantees", title: "Our Guarantees" },
  { url: "/service-area", title: "Service Area" },
  { url: "/blog", title: "Blog" },
  { url: "/all-offers", title: "All Offers" },
  { url: "/privacy-policy", title: "Privacy Policy" },
];

async function fetchServices(): Promise<Service[]> {
  try {
    const res = await fetch(
      `${API_URL}/api/services?where[active][equals]=true&where[hasPage][equals]=true&limit=1000&depth=0`,
    );
    if (res.ok) {
      const data = await res.json();
      return data.docs || [];
    }
  } catch (error) {
    console.error("Error fetching services:", error);
  }
  return [];
}

async function fetchPosts(): Promise<Post[]> {
  try {
    const res = await fetch(
      `${API_URL}/api/posts?where[_status][equals]=published&limit=1000&depth=0`,
    );
    if (res.ok) {
      const data = await res.json();
      return data.docs || [];
    }
  } catch (error) {
    console.error("Error fetching posts:", error);
  }
  return [];
}

async function fetchJobs(): Promise<Job[]> {
  try {
    const res = await fetch(
      `${API_URL}/api/jobs?where[active][equals]=true&limit=1000&depth=0`,
    );
    if (res.ok) {
      const data = await res.json();
      return data.docs || [];
    }
  } catch (error) {
    console.error("Error fetching jobs:", error);
  }
  return [];
}

export const GET: APIRoute = async () => {
  const now = new Date().toISOString();

  const [services, posts, jobs] = await Promise.all([
    fetchServices(),
    fetchPosts(),
    fetchJobs(),
  ]);

  const allUrls: { url: string; lastmod: string }[] = [];

  for (const page of staticPages) {
    allUrls.push({ url: `${SITE_URL}${page.url}`, lastmod: now });
  }

  for (const service of services.filter((s) => s.slug)) {
    allUrls.push({
      url: `${SITE_URL}/plumbing-services/${service.slug}`,
      lastmod: service.updatedAt || now,
    });
  }

  for (const post of posts.filter((p) => p.slug)) {
    allUrls.push({
      url: `${SITE_URL}/blog/${post.slug}`,
      lastmod: post.updatedAt || now,
    });
  }

  for (const job of jobs.filter((j) => j.slug)) {
    allUrls.push({
      url: `${SITE_URL}/job/${job.slug}`,
      lastmod: job.updatedAt || now,
    });
  }

  const rows = allUrls
    .map(
      (item) => `<tr>
<td><a class="url" href="${item.url}">${item.url}</a></td>
<td class="lastmod">${item.lastmod}</td>
</tr>`,
    )
    .join("\n");

  const html = `<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>XML Sitemap</title>
<style>
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
  color: #333;
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
}
h1 {
  color: #1a1a1a;
  font-size: 36px;
  margin-bottom: 10px;
}
.intro {
  margin-bottom: 40px;
  font-size: 16px;
  color: #666;
}
table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 20px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}
th {
  background: #f4f4f4;
  padding: 12px;
  text-align: left;
  font-weight: 600;
}
td {
  padding: 12px;
  border-bottom: 1px solid #eee;
}
tr:hover {
  background: #f9f9f9;
}
.url {
  color: #0066cc;
  text-decoration: none;
}
.url:hover {
  text-decoration: underline;
}
.lastmod {
  color: #666;
  font-size: 14px;
}
</style>
</head>
<body>
<h1>XML Sitemap</h1>
<div class="intro">
This is a sitemap generated by Evergreen Services to allow search engines to better index this website's content.
</div>
<table>
<tbody>
<tr>
<th>URL</th>
<th>Last Modified</th>
</tr>
${rows}
</tbody>
</table>
</body>
</html>`;

  return new Response(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
    },
  });
};
